"""add_agent_availibility_and_conversation_state

Revision ID: 0bfc0912ab56
Revises: ed359990c83b
Create Date: 2026-09-10 23:07:51.824686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bfc0912ab56'
down_revision: Union[str, Sequence[str], None] = 'ed359990c83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
