"""add_postgis_geometry_to_properties

Revision ID: 6b20d2119d06
Revises: 4f9c2d1a8b70
Create Date: 2026-10-04 16:28:55.190789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '6b20d2119d06'
down_revision: Union[str, Sequence[str], None] = '4f9c2d1a8b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The PostGIS package may be installed on the server without being enabled
    # in this database. Geometry columns require the extension to be present.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.add_column('properties', sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('properties', sa.Column('amenities', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('properties', sa.Column('image_urls', sa.ARRAY(sa.String()), nullable=True))
    op.add_column(
        'properties',
        sa.Column(
            'qdrant_indexed',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.create_index('idx_properties_location', 'properties', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_properties_location', table_name='properties', postgresql_using='gist')
    op.drop_column('properties', 'qdrant_indexed')
    op.drop_column('properties', 'image_urls')
    op.drop_column('properties', 'amenities')
    op.drop_column('properties', 'location')
    # ### end Alembic commands ###
